# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-23 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
