# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-26 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='desc',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
